package com.dhcc.scm.ws.his.dhcclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-03-27T13:50:57.361+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "SCI", 
                  wsdlLocation = "http://10.0.8.113/DTHealth/web//web.DHCST.SoapService.SCIService.CLS?WSDL=1",
                  targetNamespace = "http://tempuri.org") 
public class SCI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org", "SCI");
    public final static QName SCISoap = new QName("http://tempuri.org", "SCISoap");
    static {
        URL url = null;
        try {
            url = new URL("http://10.0.8.113/DTHealth/web//web.DHCST.SoapService.SCIService.CLS?WSDL=1");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SCI.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.0.8.113/DTHealth/web//web.DHCST.SoapService.SCIService.CLS?WSDL=1");
        }
        WSDL_LOCATION = url;
    }

    public SCI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SCI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SCI() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SCI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SCI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SCI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SCISoap
     */
    @WebEndpoint(name = "SCISoap")
    public SCISoap getSCISoap() {
        return super.getPort(SCISoap, SCISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SCISoap
     */
    @WebEndpoint(name = "SCISoap")
    public SCISoap getSCISoap(WebServiceFeature... features) {
        return super.getPort(SCISoap, SCISoap.class, features);
    }

}
