package com.dhcc.scm.ws.his.dhcclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-03-27T13:50:57.178+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org", name = "SCISoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SCISoap {

    @WebResult(name = "INPOHHImportResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "INPOHHImport", targetNamespace = "http://tempuri.org", className = "com.dhcc.pms.ws.his.dhcclient.INPOHHImport")
    @WebMethod(operationName = "INPOHHImport", action = "http://tempuri.org/web.DHCST.SoapService.SCIService.INPOHHImport")
    @ResponseWrapper(localName = "INPOHHImportResponse", targetNamespace = "http://tempuri.org", className = "com.dhcc.pms.ws.his.dhcclient.INPOHHImportResponse")
    public com.dhcc.scm.ws.his.dhcclient.OperateResult inpohhImport(
        @WebParam(name = "Input", targetNamespace = "http://tempuri.org")
        com.dhcc.scm.ws.his.dhcclient.SCIInpoUmInfoRtMain input
    );
}
