package com.dhcc.scm.ws.ven.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-15T10:13:52.365+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "OrderStateWServiceService", 
                  wsdlLocation = "http://127.0.0.1:8080/pms/ws/orderStateWService?wsdl",
                  targetNamespace = "http://ven.ws.pms.dhcc.com/") 
public class OrderStateWServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ven.ws.pms.dhcc.com/", "OrderStateWServiceService");
    public final static QName OrderStateWServiceServiceHttpSoap12Endpoint = new QName("http://ven.ws.pms.dhcc.com/", "OrderStateWServiceServiceHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/pms/ws/orderStateWService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderStateWServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/pms/ws/orderStateWService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderStateWServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderStateWServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderStateWServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderStateWServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderStateWServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderStateWServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderStateWServiceInterface
     */
    @WebEndpoint(name = "OrderStateWServiceServiceHttpSoap12Endpoint")
    public OrderStateWServiceInterface getOrderStateWServiceServiceHttpSoap12Endpoint() {
        return super.getPort(OrderStateWServiceServiceHttpSoap12Endpoint, OrderStateWServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderStateWServiceInterface
     */
    @WebEndpoint(name = "OrderStateWServiceServiceHttpSoap12Endpoint")
    public OrderStateWServiceInterface getOrderStateWServiceServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(OrderStateWServiceServiceHttpSoap12Endpoint, OrderStateWServiceInterface.class, features);
    }

}
