package com.dhcc.scm.ws.ven.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-15T10:13:52.316+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ven.ws.pms.dhcc.com/", name = "OrderStateWServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface OrderStateWServiceInterface {

    @WebResult(name = "operateResult", targetNamespace = "http://ven.ws.pms.dhcc.com/", partName = "operateResult")
    @WebMethod
    public OperateResult deliver(
        @WebParam(partName = "deliveritms", name = "deliveritms")
        VenDeliveritmArray deliveritms
    );

    @WebResult(name = "operateResult", targetNamespace = "http://ven.ws.pms.dhcc.com/", partName = "operateResult")
    @WebMethod
    public OperateResult getVenInc(
        @WebParam(partName = "venIncWeb", name = "venIncWeb")
        VenIncWeb venIncWeb
    );

    @WebResult(name = "orderWebVos", targetNamespace = "http://ven.ws.pms.dhcc.com/", partName = "orderWebVos")
    @WebMethod
    public OrderWebVoArray listOrderWS(
        @WebParam(partName = "passWord", name = "passWord")
        java.lang.String passWord,
        @WebParam(partName = "userName", name = "userName")
        java.lang.String userName
    );

    @WebResult(name = "return", targetNamespace = "http://ven.ws.pms.dhcc.com/", partName = "return")
    @WebMethod
    public OperateResult recievedMsg(
        @WebParam(partName = "orderId", name = "orderId")
        long orderId
    );
}
