package com.dhcc.scm.ws.his.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-08-07T11:45:39.253+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.dhcc.com", name = "SCMSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SCMSoap {

    @WebResult(name = "GetVendor2Result", targetNamespace = "")
    @RequestWrapper(localName = "GetVendor2", targetNamespace = "http://www.dhcc.com", className = "com.dhcc.pms.ws.his.client.GetVendor2")
    @WebMethod(operationName = "GetVendor2", action = "http://www.dhcc.com/web.DHCST.SoapService.SCMDataExchange.GetVendor2")
    @ResponseWrapper(localName = "GetVendor2Response", targetNamespace = "http://www.dhcc.com", className = "com.dhcc.pms.ws.his.client.GetVendor2Response")
    public java.lang.String getVendor2(
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type
    );

    @WebResult(name = "GetVendorResult", targetNamespace = "")
    @RequestWrapper(localName = "GetVendor", targetNamespace = "http://www.dhcc.com", className = "com.dhcc.pms.ws.his.client.GetVendor")
    @WebMethod(operationName = "GetVendor", action = "http://www.dhcc.com/web.DHCST.SoapService.SCMDataExchange.GetVendor")
    @ResponseWrapper(localName = "GetVendorResponse", targetNamespace = "http://www.dhcc.com", className = "com.dhcc.pms.ws.his.client.GetVendorResponse")
    public com.dhcc.scm.ws.his.client.HisVendor getVendor(
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type
    );

    @WebResult(name = "GetLocResult", targetNamespace = "")
    @RequestWrapper(localName = "GetLoc", targetNamespace = "http://www.dhcc.com", className = "com.dhcc.pms.ws.his.client.GetLoc")
    @WebMethod(operationName = "GetLoc", action = "http://www.dhcc.com/web.DHCST.SoapService.SCMDataExchange.GetLoc")
    @ResponseWrapper(localName = "GetLocResponse", targetNamespace = "http://www.dhcc.com", className = "com.dhcc.pms.ws.his.client.GetLocResponse")
    public com.dhcc.scm.ws.his.client.HisCtlocList getLoc();

    @WebResult(name = "GetLoc2Result", targetNamespace = "")
    @RequestWrapper(localName = "GetLoc2", targetNamespace = "", className = "com.dhcc.pms.ws.his.client.GetLoc2")
    @WebMethod(operationName = "GetLoc2", action = "http://www.dhcc.com/web.DHCST.SoapService.SCMDataExchange.GetLoc2")
    @ResponseWrapper(localName = "GetLoc2Response", targetNamespace = "http://www.dhcc.com", className = "com.dhcc.pms.ws.his.client.GetLoc2Response")
    public java.lang.String getLoc2();
}
